version: "3.8"
services:
  rcrp_ui:
    build:
      context: ./client-app
      dockerfile: Dockerfile
    container_name: rcrp_ui
    image: rcrp_ui:latest
    ports:
      - 3000:3000

  rcrp_api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: rcrp_api
    image: rcrp_api:latest
    ports:
      - 5000:5000
    volumes:
      - logs:/usr/src/app/logs

networks:
  default:
    external: true
    name: rcrp_network
volumes:
  logs:
    external:
      name: logs
