version: "3.8"
services:
  rcrp_ui:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: rcrp_ui
    image: rcrp_ui:latest
    ports:
      - ${NGINX_PORT}:${NGINX_PORT}
    environment:
      - NGINX_PORT=${NGINX_PORT}
      - NGINX_API=${NGINX_API}
      - NGINXTEMPLATE=development
networks:
  default:
    external:
      name: rcrp_network
