version: "3.8"
services:
  rcrp_ui:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: rcrp_ui
    image: rcrp_ui:latest
    ports:
      - 3000:3000
networks:
  default:
    external:
      name: rcrp_network
